### ISSUE TITLE
Wondering why the axios request in Login.js is a Post vs a Get?

### ISSUE THREAD

**Issue by jbird33** [jbird33/project3-frontend#1]
Just asking why the axios request in my Login.js is a axios.post instead of an axios.get to get the user logged in. In Project Wayfarer, it was a post but, we never fully completed that work for Login. 

handleSubmit = (event) => {
        event.preventDefault()
        // Not sure if this is a post or a get here...
        axios.post("localhost URL here", this.state.user)
            .then(response => {
                console.log("Logged In User!!")
                console.log(response)
                // Not sure what below does or where this came from response.user.user.id  
                this.props.history.push(`/profile/${response.user.user.id}`)
            })
            .catch(err => {
                console.log(err)
            })
    }

**Comment by CRHarding** [comment]
The main difference between a `get` and a `post` request is that `get` requests send a request and get data back, a `post` request sends data along with the request. Your `axios.post` line is sending in `this.state.user` which would make it a post request. Which makes sense, you have to send a users username (or email or what have you) along with their password to make sure that they have the correct credentials.

**Comment by jbird33** [comment]
Ok, very good. thank you very much!

**Comment by jbird33** [comment]
Understood!
