### ISSUE TITLE
Started server on Back-End and getting errors in my browser console that we've never seen before.

### ISSUE THREAD

**Issue by jbird33** [jbird33/project3-frontend#2]
![image](https://user-images.githubusercontent.com/83088409/122287559-aefb3300-ceb6-11eb-9245-1c9b665ec381.png)

1We fixed the index.js issue circled in the picture so disregard.
2. Getting error that says my localhost:3001 origin is blocked by CORS policy.

We did try and Google these without success:
https://www.digitalocean.com/community/questions/blocked-by-cors-policy-the-access-control-allow-origin-mean-stack
https://stackoverflow.com/questions/46277295/xmlhttprequest-blocked-by-cors-policy

**Comment by CRHarding** [comment]
Hmmmmm, CORS errors can be the worst because it could be a number of different issues that are causing them. First things first, are you sure that you have a route set up in your backend express app that is correctly handling /signup routes?

**Comment by margenta2** [comment]
No, I can't say we're sure the route is set up correctly. 
Here is our route
![image](https://user-images.githubusercontent.com/82845203/122290499-6bee8f00-ceb9-11eb-8ce6-9e8e9b939af0.png)

**Comment by margenta2** [comment]
I'm not sure the controller is right either. We're trying to piece together what we've done before and what we did on project wayfarer
![image](https://user-images.githubusercontent.com/82845203/122290798-b6700b80-ceb9-11eb-9106-a4ce3ab12de7.png)

**Comment by CRHarding** [comment]
Looking into this currently, hang tight!

**Comment by CRHarding** [comment]
Alright, I think I've got it:

In your server.js how are you linking the route file to your express app? You're using the `app.use('/users', routes.users);`, but when you try and hit the signup route you're going to `localhost:3001/signup`...

**Comment by CRHarding** [comment]
The `app.use()` is like the initial instruction when baking, ie you start with 500 grams of flour and then add in x, y, z, that's what the server.js app.use is doing, it's setting up your initial route which you then add on top of, so when you say `app.use('/users', routes.users)` every route that has a `/users` on it will be redirected to your users router. Right now you're going to `localhost:3001/signup`, but there isn't a `localhost:3001/signup`, there is, however, a `localhost:3001/users/signup`

**Comment by margenta2** [comment]
In our axios.post we changed the url to be localhost:3001/users/signup but it still doesn't seem to be working. Do we need to install cors? We saw that in another resource.

**Comment by CRHarding** [comment]
Are there any other errors being thrown / have the errors changed after adjusting the route? I would say add in some console.logs to your signup route in your controller to make sure that your front end is hitting the correct route in your back end and start digging into the issue from there. Isolating where the error is being thrown is the number one goal at this point.

**Comment by jbird33** [comment]
The only errors we get so far is the blocked by CORS policy. I noticed in project Wayfarer on the server.js there is an const cors = require('cors'); and another reference to cors? Do we need to install npm install cors? or something?

**Comment by CRHarding** [comment]
I'm not seeing any cors in your backend so I would ignore that. CORS issues often come about because your routing /  controllers aren't set up properly. Have you tried throwing in any console logs into your controller to make sure that your signup controller is actually being hit by your front end?

**Comment by jbird33** [comment]
![image](https://user-images.githubusercontent.com/83088409/122296238-cc80ca80-cebf-11eb-90e9-7dd21ed51bed.png)
 
So, we console logged into the two above places and get nothing in return except blocked by CORS policy in browser and nothing on the backend console when I try axios.post("http://localhost:3001/users/login", this.state.user)

**Comment by CRHarding** [comment]
Hold up a tick, everything we've seen so far has had to do with signup, not login, make sure your console.logs are in the correct controller.

**Comment by margenta2** [comment]
Sorry, we've been switching between sign up and log in to see if we can get either to work. Same issue on both.

**Comment by CRHarding** [comment]
Can you do something before we get a bit more radical, could you switch your front end routes to use https? I doubt it'll do anything but it's worth a shot (so `https://localhost:3001/users/signup`)

**Comment by CRHarding** [comment]
And check your backend terminal (where your backend server is running), it's very unlikely that you're not getting any indication that there's an error being thrown somewhere.

**Comment by davidmagbee** [comment]
Be sure to close the issue ticket once your issue is resolved. @jbird33 @margenta2
