### ISSUE TITLE
Drop Down Issue

### ISSUE THREAD

**Issue by margenta2** [jbird33/project3-frontend#3]
We want the user to be able to choose a favorite movie on their profile page from a drop down list. Once that movie is chosen we want it to stick on the page. We have  a user table set up with a fk of movie id that corresponds to the movie id on the movie table. We aren't able to figure out how to create a drop down list that pulls from the back end and shows the current selection with the movie title. 

We're tried these resources:
[DropDowns](http://www.mattmorgante.com/technology/dropdown-with-reacthttps://blog.logrocket.com/building-a-custom-dropdown-menu-component-for-react-e94f02ced4a1/)
[Medium](https://medium.com/how-to-react/react-select-dropdown-tutorial-using-react-select-51664ab8b6f3)
[LogRocket](https://blog.logrocket.com/building-a-custom-dropdown-menu-component-for-react-e94f02ced4a1/)

**Comment by CRHarding** [comment]
Give this a shot, if you check out the bonus section from pokemon they have the ask for the bonus: https://git.generalassemb.ly/cfg-seir-2/Pokemon-Express#update-player-controller--view and then in the solution code you can see the view file should look something like so: https://git.generalassemb.ly/cfg-seir-2/Pokemon-Express/blob/master/solution-code/day6/pokemon-app/views/player/profile.ejs (paying particular attention to the dropdown / selected attribute) and then in the controller you'd be sending all of the options over: https://git.generalassemb.ly/cfg-seir-2/Pokemon-Express/blob/master/solution-code/day6/pokemon-app/controllers/player.js (the renderProfile method is the one to look at).

**Comment by margenta2** [comment]
Instead of a for loop, should we be using a map function?
